# Generated by Django 5.2.6 on 2025-10-01 06:10

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_alter_imagenproducto_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='qr_imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imgpagoqr'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
