# Generated by Django 5.2.6 on 2026-04-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_alter_metodopago_qr_imagen_alter_pedido_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
