# Generated by Django 5.2.6 on 2025-10-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_alter_metodopago_qr_imagen_alter_pedido_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
